### PR TITLE
Fixed everything

### PR DESCRIPTION
**Pull request by squiffy**

### CODE REVIEW

**Comment by gabe-k** [comment]
Hi Squiffy,

Thanks a lot for your contribution! Unfortunately I'm encountering an issue where with your new changes the app server does not appear to be starting. Any idea what might be causing this? I'll be sure to merge your request as soon as we can resolve this issue.

Thanks a ton!
Gabe Kirkpatrick

**Comment by squiffy** [comment]
Sorry I dont know how to program. real web devs use mips

**Comment by gabe-k** [comment]
Unfortunately this is for the iPhone iOS platform which is based on the Z80 CPU processor architecture assembly. Thank you for your work though!

**Comment by squiffy** [comment]
o will do

**Pull request closed without merging**
